#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, BreakSwitch,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 2 Remotes -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Left and the Right joysticks on Remote Control 1 to run the robot using     *|
|*  "tank control". The Group 6 buttons on the top-right of Remote Control 2 are used to raise and    *|
|*  lower the arm.                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

struct
{
	unsigned int milli;
	unsigned int tStart;
} Timer;

bool timerPassed( Timer* pThis )
{
	return nPgmTime >= pThis->tStart + pThis->milli;
}

void startTimer( Timer* pThis, unsigned int milli )
{
	pThis->tStart = nPgmTime;
	pThis->milli = milli;
}

int corrected(int channel)
{
	if (vexRT[channel] >= 100)
		return 127;
	else if (vexRT[channel] <= -100)
		return -127;
	else
		return vexRT[channel];
}

task BREAKS()
{
	while(true)
	{
		if (SensorValue[BreakSwitch] || vexRT[Btn8U])
			StopAllTasks();
	}
}




task main()
{
	StartTask(BREAKS);

	Timer tim;

	bool downed = false;

	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0

  while(true)
  {
  	writeDebugStreamLine("CRight: %d, CLeft: %d",corrected(Ch2), corrected(Ch2));
  	if ((corrected(Ch2) == -127 || corrected(Ch2) == 127) && ((corrected(Ch3) == -127 || corrected(Ch3)== 127)))
  	{
			if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
			{
				// Move Forward
			  motor[rightMotor] = -corrected(Ch2);
	      motor[leftMotor] = -corrected(Ch3);
			}
			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
			{
				// Turn slightly right
			  motor[rightMotor] = -(corrected(Ch2) - 20);
	      motor[leftMotor] = -corrected(Ch3);
			}
			else	// Only runs if leftEncoder has counted more encoder counts
			{
				// Turn slightly left
				motor[rightMotor] = -corrected(Ch2);
	      motor[leftMotor] = -(corrected(Ch3) - 20);
			}
		}
		else
		{
			motor[rightMotor] = -corrected(Ch2);
	    motor[leftMotor] = -corrected(Ch3);
		}

    //Arm Control with Remote Control 2
    if(vexRT[Btn6U])
    {
      motor[armMotor] = -60;
      downed = false;
    }
    else if(vexRT[Btn6D])
    {
      motor[armMotor] = 40;
      downed = true;
      startTimer( &tim, 300 );
    }
    else
    {
      motor[armMotor] = downed ? -15:0;
      if (timerPassed( &tim ))
      	downed = false;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
