#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 2 Remotes -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Left and the Right joysticks on Remote Control 1 to run the robot using     *|
|*  "tank control". The Group 6 buttons on the top-right of Remote Control 2 are used to raise and    *|
|*  lower the arm.                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++



task main()
{


	bool downed = false;

	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0

	//Nonna vals
	int SensorRL = 0;
	int SensorLL = 0;
	float NonnakalkR = 0.0 ;
	float NonnakalkL = 0.0 ;
	int testspeed = -126;

  while(true)
  {
  	//hreyfu etta seinna nonni ;)

  	//motor[rightMotor] = -vexRT[Ch2];//126;//-vexRT[Ch2];
    //motor[leftMotor] = -vexRT[Ch3];//126;//-vexRT[Ch3];

    //writeDebugStreamLine(" Right: %d, Left: %d", -vexRT[Ch2], -vexRT[Ch3]);

    //spooky Bits
    //you know what im saying

    NonnakalkR=NonnakalkR + testspeed/(SensorRL/SensorValue[rightEncoder]);
    NonnakalkL=NonnakalkL + testspeed/(SensorLL/SensorValue[leftEncoder]);
    //writeDebugStreamLine(" RightN: %f, LeftN: %f", NonnakalkR, NonnakalkL);
    //writeDebugStreamLine(" testspeed: %f, SensorRL: %f, SensorLL: %f", testspeed, NonnakalkL, SensorValue[rightEncoder], SensorValue[leftEncoder], SensorLL);
    //writeDebugStreamLine(" SensorValueR: %f, SensorValueL: %f", SensorValue[rightEncoder], SensorValue[leftEncoder]);
    motor[rightMotor] = testspeed +floor(NonnakalkR) ;
    motor[leftMotor] = testspeed +floor(NonnakalkL) ;

    NonnakalkR=NonnakalkR-floor(NonnakalkR);
    NonnakalkL=NonnakalkL-floor(NonnakalkL);



		//if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
		//{
			// Move Forward
		  //motor[rightMotor] = -vexRT[Ch2];
      //motor[leftMotor] = -vexRT[Ch3];
		//}
		//else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
		//{
			// Turn slightly right
		  //motor[rightMotor] = -(vexRT[Ch2] - (vexRT[Ch2] * 0.25));
      //motor[leftMotor] = -vexRT[Ch3];
		//}
		//else	// Only runs if leftEncoder has counted more encoder counts
		//{
			// Turn slightly left
			//motor[rightMotor] = -vexRT[Ch2];
      //motor[leftMotor] = -(vexRT[Ch3] - (vexRT[Ch3] * 0.25));
		//}


    //Arm Control with Remote Control 2
    if(vexRT[Btn6U])
    {
      motor[armMotor] = -60;
      downed = false;
    }
    else if(vexRT[Btn6D])
    {
      motor[armMotor] = 40;
      downed = true;
    }
    else
    {
      motor[armMotor] = downed ? -15:0;

    }

  	//More spooky bits

    SensorRL = SensorValue[rightEncoder];
    SensorLL = SensorValue[leftEncoder];
    //writeDebugStreamLine("encR: %f, encL: %f", SensorRL, SensorLL);
    //writeDebugStreamLine("sensR: %f, sensL: %f", SensorValue[rightEncoder], SensorValue[leftEncoder]);
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
