#pragma config(Sensor, dgtl4,  breakSwitch,    sensorDigitalIn)
#pragma config(Sensor, dgtl8,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 2 Remotes -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Left and the Right joysticks on Remote Control 1 to run the robot using     *|
|*  "tank control". The Group 6 buttons on the top-right of Remote Control 2 are used to raise and    *|
|*  lower the arm.                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

bool downed = false;


	//Nonna vals
	int SensorRL = 0;
	int SensorLL = 0;
	float NonnakalkR = 0.0 ;
	float NonnakalkL = 0.0 ;
	int testspeed = 50;
	int direction = testspeed/abs(testspeed);
	int breaklast = 1;
	float Nout1= 0;
	float Nout2= 0;

	//times
	float Ntime1 = 0;
	float Ntime2 = 0;
	float Ntime3 = 0;
	float Vidmid = 1260; //hvada tima einn snuningur a ad taka
	int Stateout = 0; //ef thetta verdur 2 haettir calibrationid
	int i=1;

task main()
{

	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0
	clearDebugStream();
	for ( i=1; i<2000; i++) {
		motor[rightMotor] = testspeed;
		motor[leftMotor] = testspeed;
	}
	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0
	Ntime3 = nPgmTime;
  while(Stateout<2)
  {
  	if(!SensorValue[breakSwitch])
  	{
  		break;
  	}
		Stateout = 0;
  	if (-SensorValue[rightEncoder]<800)
  	{
  		motor[rightMotor] = testspeed;
  		Ntime1=((float)nPgmTime);
  	}
  	else if (-SensorValue[rightEncoder]==800)
  	{
  		//Ntime1=((float)nPgmTime+Ntime2)/2;
  		writeDebugStreamLine(" Right: %d, Time %d", SensorValue[rightEncoder], Ntime1);
  		motor[rightMotor] = testspeed;
  	}
  	else
  	{
  		motor[rightMotor] = 0;
  		Stateout = Stateout + 1;
  	}



  	if (direction*SensorValue[leftEncoder]<800)
  	{
  		motor[leftMotor] = testspeed;
  		Ntime2=((float)nPgmTime);
  	}

  	else if (SensorValue[leftEncoder]==800)
  	{
  		//Ntime2=((float)nPgmTime+Ntime2)/2;
  		writeDebugStreamLine(" left: %d, Time %d", SensorValue[leftEncoder], Ntime2);
  		motor[leftMotor] = testspeed;
  	}
  	else
  	{
  		motor[leftMotor] = 0;
  		Stateout = Stateout + 1;
  	}


  }
  writeDebugStreamLine(" left: %f, right: %f , Ntime3: %f", Ntime2, Ntime1,Ntime3);
  Ntime1 = (Ntime1 - Ntime3);
	Ntime2 = (Ntime2 - Ntime3);
	if (Ntime1 >Ntime2){
		Ntime3=Ntime2;
		//Nout1=testspeed-(-126*(Ntime1-Ntime2))-testspeed-(-126*(Ntime2-Ntime1));
	}
	else
	{
		Ntime3=Ntime1;
		//Nout2=testspeed-(-126*(Ntime2-Ntime1))-testspeed-(-126*(Ntime1-Ntime2));
	}
	Ntime1 = Ntime1/Ntime3;
	Ntime2 = Ntime2/Ntime3;
	writeDebugStreamLine(" left: %f, right %f", Ntime2, Ntime1);
	writeDebugStreamLine(" left: %i, right %i", testspeed*Ntime2, testspeed*Ntime1);
	writeDebugStreamLine(" left: %i, right %i", testspeed-(-testspeed*2*(Ntime2-Ntime1)), testspeed-(-testspeed*2*(Ntime1-Ntime2));
	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0
	Nout1=2*(-testspeed*(2-abs(direction*testspeed/126))*(Ntime1-Ntime2));//(-testspeed*(2-abs(testspeed/126))*(Ntime1-Ntime2));
	Nout2=2*(-testspeed*(2-abs(direction*testspeed/126))*(Ntime2-Ntime1));//(-testspeed*(2-abs(testspeed/126))*(Ntime2-Ntime1));
	writeDebugStreamLine(" Nout2 left: %i, | Nout1 right %i",-Nout2,-Nout1;

	while(true){

		if(SensorValue[breakSwitch])
  		{if(!breaklast)
  		{
  			break;
  		}
  	}
  	breaklast= SensorValue[breakSwitch];
	}
	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[leftEncoder]  = 0;	  // Set the encoder so that it starts counting at 0
	while(abs(SensorValue[leftEncoder])< 2000){
		/*if(!SensorValue[breakSwitch])
  	{
  		break;
  	}*/
		//motor[rightMotor] = testspeed+(Nout1);
		//motor[leftMotor] = testspeed+(Nout2);
  	motor[rightMotor] = testspeed-Nout1;//(-testspeed*(2-abs(testspeed/126))*(Ntime1-Ntime2));
		motor[leftMotor] = testspeed-Nout2;//(-testspeed*(2-abs(testspeed/126))*(Ntime2-Ntime1));
	}


}


  	/*
  	Ntime0 = nPgmTime;
  	while(SensorValue[rightEncoder]<401)
  	{
  		motor[rightMotor] = 126;
  	}
  	*/
  	/*

  	---------------------------------
  	Format 1
  	---------------------------------


  	hreyfu etta seinna nonni ;)

  	//motor[rightMotor] = -vexRT[Ch2];//126;//-vexRT[Ch2];
    //motor[leftMotor] = -vexRT[Ch3];//126;//-vexRT[Ch3];

    //writeDebugStreamLine(" Right: %d, Left: %d", -vexRT[Ch2], -vexRT[Ch3]);

    //spooky Bits
    //you know what im saying

    //writeDebugStreamLine(" RightN: %f, LeftN: %f", NonnakalkR, NonnakalkL);
    //writeDebugStreamLine(" testspeed: %f, SensorRL: %f, SensorLL: %f", testspeed, NonnakalkL, SensorValue[rightEncoder], SensorValue[leftEncoder], SensorLL);
    //writeDebugStreamLine(" SensorValueR: %f, SensorValueL: %f", SensorValue[rightEncoder], SensorValue[leftEncoder]);




    //Arm Control with Remote Control 2
  	/*
    if(vexRT[Btn6U])
    {
      motor[armMotor] = -60;
      downed = false;
    }
    else if(vexRT[Btn6D])
    {
      motor[armMotor] = 40;
      downed = true;
    }
    else
    {
      motor[armMotor] = downed ? -15:0;

    }*/




		/*
  	//More spooky bits

    SensorRL = SensorValue[rightEncoder];
    SensorLL = SensorValue[leftEncoder];
    //writeDebugStreamLine("encR: %f, encL: %f", SensorRL, SensorLL);
    //writeDebugStreamLine("sensR: %f, sensL: %f", SensorValue[rightEncoder], SensorValue[leftEncoder]);

    */

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
